language: bash
services: docker
script:
- docker run --rm -v "$PWD":/go/src/flash-socket-policy-docker -w /go/src/flash-socket-policy-docker golang:1.13-alpine3.10 ./build.sh
deploy:
  provider: releases
  token:
    secure: ol2MP+4WRrb9ZCpSMWJ/mtRJGWtf3H/GUa51gw7VGwl07w+gMrxFg7uJhmfmkFkFnBvb3kEmZ/lwrqkXOoTMaA0wpYSA0AUhjuPy0+XvuSgydq1XhDE1NU8zU1wXgv3tzgakJiEm88RbwvMPz1vgHYrt/ffqjxMz4Fr9i/gZisB5joJkwTPcpQZkLNlqYwnuG1k+pBbXKWDYOBgdAR6RFfnnJzgLPuCzDI3/TljN7b8/2dAQ3wflj7XLQjQTO32zJq37+YJkQ7YPBdqMn2Qpbcj3doy19FeZ3QXRiE+fmKnVMB23qAxpGjjbTVogC38DxfnYt1V54gO/ltNPs2vD/QxFcLuQRupd6mF1h8Hpz9tFf0LBRKYaaNgDNeJvHu66U1F60+E9LZHN8F5MIUV9hu0UT/rOIyQ0p07ka1NXnSl1lZOgThJn6B1VvjAaXFDT5Sr7uADJFK9qso0OJfzRYtmhFVQmqbkoKxl7I7J5Uy00cS1nI/ipa5vmjm/DaZ3H2PBVxE4zZSAiABjSTePnuO8ARhLO40qZHEnqmgtfdHHX1RznqWfkyvAeCcUeJ96pOi8+DNuiAB+ZmVaLEh6nE8M+DJBNaXc7zTGX8Hfe93roPxCyAs/lotQz2+hHJs0SV0Wlj74Z/5QbuMLFZUp7sv2dDLfWjqa6VoSGfDnRFyg=
  file: build/gofsp
  skip_cleanup: true
  on:
    repo: ohze/flash-socket-policy-docker
    tags: true
